spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hirenest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

jwt:
  secret: your-very-long-secret-key-here-at-least-32-characters-long
